### ISSUE TITLE
coreMQTT-Agent

### ISSUE THREAD

**Issue by n8o** [espressif/esp-freertos-coremqtt#1]
Any plans to support coreMQTT-Agent?

https://freertos.org/Documentation/api-ref/coreMQTT-Agent/docs/doxygen/output/html/index.html

**Comment by fdobrovolny** [comment]
In the `esp-aws-iot` there is a ported coreMQTT-Agent (https://github.com/espressif/esp-aws-iot/tree/master/libraries), but no examples trying to make it work now.
